# Generated by Django 4.2.8 on 2024-01-31 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posthistory',
            name='response',
            field=models.JSONField(blank=True, max_length=100, null=True),
        ),
    ]
