# Generated by Django 4.2.8 on 2024-01-31 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_posthistory_response'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostHistory',
        ),
    ]
